# Generated by setup script on Mon Jan 26 02:27:47 UTC 2026
project_name = "questionnaire"
environment  = "dev"
location     = "westus2"

tags = {
  Project     = "Adaptive Questionnaire System"
  Environment = "Development"
  ManagedBy   = "Terraform"
}
